from dotenv import load_dotenv
from pathlib import Path
import os

load_dotenv()

GEMINI_API_KEY=os.getenv('GEMINI_API_KEY')
YT_LINKS=os.getenv("YT_LINKS")
VIDEO_OUTPUT_DIR=os.getenv("VIDEO_OUTPUT_DIR")
PROCESSED_VIDEO_OUTPUT_DIR=os.getenv("PROCESSED_VIDEO_OUTPUT_DIR")
EMBEDDING_MODEL=os.getenv("EMBEDDING_MODEL")
EMBEDDING_MODEL_API_KEY=os.getenv("EMBEDDING_MODEL_API_KEY")
GENERATOR_MODEL=os.getenv("GENERATOR_MODEL")
GENERATOR_MODEL_URL=os.getenv("GENERATOR_MODEL_URL")
GENERATOR_MODEL_API_KEY=os.getenv("GENERATOR_MODEL_API_KEY")
SCENE_DESCRIBER_MODEL=os.getenv("SCENE_DESCRIBER_MODEL")
SCENE_DESCRIBER_URL=os.getenv("SCENE_DESCRIBER_URL")
QDRANT_COLLECTION_NAME=os.getenv("QDRANT_COLLECTION_NAME")
HF_TOKEN=os.getenv("HF_TOKEN")
